files = Split('''
    clc.cpp
    config.cpp
''')
env = Environment(CXXFLAGS='-Wall -O2 -std=c++17 -Wextra',
                  CPPDEFINES='RELEASE')
exe = env.Program('clc', files)
env.Install('../dist', exe)
