[package]
name = "clc"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3 # 3 is fastest binary; use "s" for smallest
lto = true

[dependencies]
state = "^0.5"
term_size = "^0.3"

[dependencies.clap]
version = "^4"
features = [ "derive", "wrap_help",]
